/// <reference types="next" />
/// <reference types="next/image-types/global" />

/**
 * This file ensures Next.js types are picked up by TypeScript.
 * It is normally generated by Next, but including it avoids first-run hiccups.
 */
